"""add_email_password_to_customers

Revision ID: 698cf399488d
Revises: 6bf3f0e285f0
Create Date: 2026-08-17 22:57:27.991312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698cf399488d'
down_revision = '6bf3f0e285f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
